### ISSUE TITLE
media-libs/gst-plugins-bad-1.27.2 fails in configure

### ISSUE THREAD

**Issue by hlandgarten** [Qeenon/mawa#52]
Dependency libchromaprint skipped: feature chromaprint disabled
Dependency pangocairo skipped: feature closedcaption disabled
Dependency json-glib-1.0 skipped: feature codec2json disabled
Dependency lcms2 skipped: feature colormanagement disabled
Dependency libcurl skipped: feature curl disabled
Dependency libxml-2.0 skipped: feature dash disabled
Dependency libdc1394-2 skipped: feature dc1394 disabled
Dependency directfb skipped: feature directfb disabled
Dependency openssl skipped: feature dtls disabled
Dependency libcrypto skipped: feature dtls disabled
Library faac skipped: feature faac disabled
Header "faac.h" has symbol "faacEncOpen" : NO 
Dependency fdk-aac skipped: feature fdkaac disabled
Dependency fluidsynth skipped: feature fluidsynth disabled
Dependency google_cloud_cpp_storage skipped: feature gs disabled
Dependency gtk+-3.0 skipped: feature gtk3 disabled
Dependency gtk+-wayland-3.0 skipped: feature gtk3 disabled
Dependency dssim skipped: feature iqa disabled
Fetching value of define "_MSC_VER" : (undefined) 
Dependency webrtc-audio-coding-1 skipped: feature isac disabled
Dependency lc3 skipped: feature lc3 disabled
Run-time dependency lcevc_dec found: NO (tried pkgconfig and cmake)

../gst-plugins-bad-1.27.2/ext/lcevcdecoder/meson.build:29:16: ERROR: Dependency "lcevc_dec" not found, tried pkgconfig and cmake

**Comment by Miezhiko** [comment]
@hlandgarten yes, sorry, messed a bit, work in progress...

**Comment by Miezhiko** [comment]
this exact error should be fixed now

**Comment by Miezhiko** [comment]
https://github.com/Miezhiko/Overlay/commit/850fb6993f2f5dadb530ae923c7718f206169614

**Comment by hlandgarten** [comment]
Still failing in configure. Looks like lcevc_dec is pulled in as a runtime dependency

[build.log](https://github.com/user-attachments/files/22662286/build.log)
